spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ddan
    url: jdbc:mysql://localhost:3306/jpashop?MVCC=TRUE
    password: dnd14112
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
        default_batch_fetch_size: 20
#        show_sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace